Add fibonacci series in java
fharookshaik/fibonacci-series pull request #26
Opened 2020-10-05 14:33 UTC by AasthaGoyalgit

2020-10-05 15:59 UTC, fharookshaik commented on java_fibonacci.java.java
> +public class FibonacciSeries {
Main.java:5: error: class FibonacciSeries is public, should be declared in a file named FibonacciSeries.java
public class FibonacciSeries {
       ^
1 error

Try to improve the code by fixing the errors.

Happy Coding!!
Happy Contributing!!

2020-10-06 04:53 UTC, AasthaGoyalgit commented
Now once u check it again i have made some changes.

On Mon, Oct 5, 2020, 21:29 fharook shaik <notifications@github.com> wrote:

> *@fharookshaik* commented on this pull request.
> ------------------------------
>
> In java_fibonacci.java.java
> <https://github.com/fharookshaik/fibonacci-series/pull/26#discussion_r499706291>
> :
>
> > @@ -0,0 +1,25 @@
> +package milestone6;
> +
> +import java.util.Scanner;
> +
> +public class FibonacciSeries {
>
> Main.java:5: error: class FibonacciSeries is public, should be declared in
> a file named FibonacciSeries.java
> public class FibonacciSeries {
> ^
> 1 error
>
> Try to improve the code by fixing the errors.
>
> Happy Coding!!
> Happy Contributing!!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fharookshaik/fibonacci-series/pull/26#pullrequestreview-502201297>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APYY63HEAM3ITWQWRA3R2CLSJHUOFANCNFSM4SEYV2UQ>
> .
>

2020-10-07 11:47 UTC, fharookshaik requested changes
Changes Requested.

2020-10-07 11:47 UTC, fharookshaik commented on Java_fibonacci.java
> +         int a=1,b=1;
I'm encountering the following error after executing the program. Try changing them and add a new line after printing each fibonacci term.

Enter a number of members in series: 100
1 1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 1048576 2097152 4194304 8388608 16777216 33554432 67108864 134217728 268435456 536870912 1073741824 -2147483648 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

Happy Coding!!
Happy Contributing!!

2020-10-07 16:10 UTC, fharookshaik commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           

Complexity increasing per file
==============================
- Java_fibonacci.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781&bid=20460280)

2020-10-07 16:10 UTC, fharookshaik commented on Java_fibonacci.java
> +            BigInteger c=new BigInteger(a.add(b).toString());;
Codacy found an issue: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781)

2020-10-07 16:10 UTC, fharookshaik commented on Java_fibonacci.java
> +public class Java_fibonacci {
Codacy found an issue: [The class name 'Java_fibonacci' doesn't match '[A-Z][a-zA-Z0-9]*'](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781)

2020-10-07 16:15 UTC, fharookshaik commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- Java_fibonacci.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781&bid=20460280)

2020-10-07 16:15 UTC, fharookshaik commented on Java_fibonacci.java
> +public class Java_fibonacci {
Codacy found an issue: [The class name 'Java_fibonacci' doesn't match '[A-Z][a-zA-Z0-9]*'](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781)

2020-10-08 04:05 UTC, fharookshaik commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Java_fibonacci.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/fharookshaik/fibonacci-series/pullRequest?prid=6288781&bid=20460280)

2020-10-08 04:13 UTC, fharookshaik commented on Java_fibonacci.java
> +            BigInteger c=new BigInteger(a.add(b).toString());
Error while executing the code.


$javac milestone6/JavaFibonacci.java
milestone6/JavaFibonacci.java:14: error: cannot find symbol
        BigInteger a=new BigInteger("0");
        ^
  symbol:   class BigInteger
  location: class JavaFibonacci
milestone6/JavaFibonacci.java:14: error: cannot find symbol
        BigInteger a=new BigInteger("0");
                         ^
  symbol:   class BigInteger
  location: class JavaFibonacci
milestone6/JavaFibonacci.java:15: error: cannot find symbol
        BigInteger b=new BigInteger("1");
        ^
  symbol:   class BigInteger
  location: class JavaFibonacci
milestone6/JavaFibonacci.java:15: error: cannot find symbol
        BigInteger b=new BigInteger("1");
                         ^
  symbol:   class BigInteger
  location: class JavaFibonacci
milestone6/JavaFibonacci.java:19: error: cannot find symbol
            BigInteger c=new BigInteger(a.add(b).toString());
            ^
  symbol:   class BigInteger
  location: class JavaFibonacci
milestone6/JavaFibonacci.java:19: error: cannot find symbol
            BigInteger c=new BigInteger(a.add(b).toString());
                             ^
  symbol:   class BigInteger
  location: class JavaFibonacci
6 errors

2020-10-16 05:15 UTC, merged

2020-10-16 05:16 UTC, fharookshaik commented
Thank you for your Contribution!!

2020-10-16 05:59 UTC, fharookshaik commented
Don't forget to add your name and the programming language under the specific folders.